environment: development

server:
  scheme: http
  host: localhost
  base_url: http://localhost

database:
  require_ssl: false

redis:
  url: redis://localhost:6379

secret:
  secret_key: YkDU_%q({@QV&5-Z}SONy,7YO?[qF6F6
  token_expiration: 10
  hmac_secret: 3daad17f50d3577ae06406213073aa28e5cda75b97f5f35170e63653bbb66d8d

client_url: http://localhost:5173
