version: "3.9"
services:
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=cockroach://root@kratos-crdb:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-crdb
        target: /var/lib/crdb
        read_only: false
      - type: bind
        source: ./services/kratos/config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    ports:
      - "4455:4455"
    networks:
      - intranet
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=cockroach://root@kratos-crdb:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-crdb
        target: /var/lib/crdb
        read_only: false
      - type: bind
        source: ./services/kratos/config
        target: /etc/config/kratos
    networks:
      - intranet
  kratos-crdb:
    image: cockroachdb/cockroach:v22.2.6
    ports:
      - "26258:26257"
    command: start-single-node --insecure
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-crdb:
