server:
  port: 8080

redis:
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

email:
  host: mail.privateemail.com
  host_user: support@manifold.chat
  host_user_password: gaMm9@2t!#f9bKGmne4*Jcnz3$cBf*aV
