environment: production

server:
  scheme: https
  host: 0.0.0.0
  base_url: ""

database:
  require_ssl: true

redis:
  url: redis://127.0.0.1:6379

secret:
  secret_key: ""
  token_expiration: 0
  hmac_secret: ""

client_url: ""
